"""Apply human-reviewed schedule import decisions.

Input directory should contain:
- courses.csv / teachers.csv / classrooms.csv / class_groups.csv / teaching_tasks.csv
- import_review_items.csv generated by prepare_import_review.py and manually filled in `decision`

Safety:
- Dry-run by default.
- Use --execute to write database changes.
- Rows without decision are skipped.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from app.db.session import connect, load_db_config  # noqa: E402

ACTIVE = "ACTIVE"
DEFAULT_TEACHER_ROLE = "TEACHER"
DEFAULT_TEACHER_PASSWORD = "123456"


def apply_review(*, input_dir: Path, execute: bool = False) -> dict[str, Any]:
    if not input_dir.exists() or not input_dir.is_dir():
        raise SystemExit(f"input-dir not found: {input_dir}")

    data = {
        "courses": _index(_read_csv(input_dir / "courses.csv"), "course_code"),
        "teachers": _index(_read_csv(input_dir / "teachers.csv"), "teacher_name"),
        "classrooms": _index(_read_csv(input_dir / "classrooms.csv"), "classroom_name"),
        "class_groups": _index(_read_csv(input_dir / "class_groups.csv"), "class_name"),
        "teaching_tasks": _read_csv(input_dir / "teaching_tasks.csv"),
        "review_items": _read_csv(input_dir / "import_review_items.csv"),
    }

    decisions = [row for row in data["review_items"] if _clean(row.get("decision"))]
    plan: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []

    conn = connect(load_db_config())
    try:
        with conn.cursor() as cur:
            db = _load_db(cur)
            conn.begin()
            context = {"db": db, "data": data, "plan": plan, "skipped": skipped}
            for row in decisions:
                _apply_decision(cur, row, context, execute=execute)
            if execute:
                conn.commit()
            else:
                conn.rollback()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

    report = {
        "status": "applied" if execute else "dry_run_ok",
        "execute": execute,
        "input_dir": str(input_dir),
        "decision_count": len(decisions),
        "planned_count": len(plan),
        "skipped_count": len(skipped),
        "planned_counts": _counts(plan, "action"),
        "skipped_counts": _counts(skipped, "reason"),
        "planned_preview": plan[:80],
        "skipped_preview": skipped[:80],
    }
    (input_dir / "import_apply_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    return report


def _apply_decision(cur, row: dict[str, str], context: dict[str, Any], *, execute: bool) -> None:
    decision = _clean(row.get("decision"))
    entity_type = _clean(row.get("entity_type"))
    entity_key = _clean(row.get("entity_key"))
    review_type = _clean(row.get("review_type"))
    if decision in {"ignore", "keep_db"}:
        context["plan"].append(_plan(row, f"{decision}:{entity_type}", "不修改数据库"))
        return
    if review_type == "conflict" and decision == "use_import":
        _apply_conflict_use_import(cur, row, context, execute=execute)
        return
    if review_type == "new_item" and decision in {"create", "create_after_dependencies"}:
        if entity_type == "course":
            _create_course(cur, entity_key, context, execute=execute)
            return
        if entity_type == "teacher":
            _create_teacher(cur, entity_key, context, execute=execute)
            return
        if entity_type == "class_group":
            _create_class_group(cur, entity_key, context, execute=execute)
            return
        if entity_type == "classroom":
            _create_classroom(cur, entity_key, context, execute=execute)
            return
        if entity_type == "teaching_task":
            _create_teaching_task(cur, row, context, execute=execute)
            return
    context["skipped"].append(_skip(row, f"unsupported decision: {decision}"))


def _apply_conflict_use_import(cur, row: dict[str, str], context: dict[str, Any], *, execute: bool) -> None:
    entity_type = _clean(row.get("entity_type"))
    entity_key = _clean(row.get("entity_key"))
    field_name = _clean(row.get("field_name"))
    import_value = _clean(row.get("import_value"))
    db_id = _clean(row.get("db_id"))
    sql_map = {
        ("course", "course_name"): ("course", "name"),
        ("course", "credits"): ("course", "credits"),
        ("course", "required_hours"): ("course", "required_hours"),
        ("course", "course_type"): ("course", "course_type"),
        ("course", "required_room_type"): ("course", "required_room_type"),
        ("classroom", "classroom_type"): ("classroom", "classroom_type"),
        ("classroom", "capacity"): ("classroom", "capacity"),
        ("classroom", "status"): ("classroom", "status"),
        ("class_group", "major"): ("class_group", "major"),
        ("class_group", "department"): ("class_group", "department"),
        ("class_group", "grade"): ("class_group", "grade"),
        ("class_group", "student_count"): ("class_group", "student_count"),
    }
    target = sql_map.get((entity_type, field_name))
    if not target or not db_id:
        context["skipped"].append(_skip(row, "conflict field cannot be applied automatically"))
        return
    table, column = target
    value = _typed_value(import_value, field_name)
    context["plan"].append(_plan(row, f"update:{table}.{column}", f"{entity_key}: {column} = {value}"))
    if execute:
        cur.execute(f"UPDATE {table} SET {column} = %s WHERE id = %s", (value, db_id))


def _create_course(cur, code: str, context: dict[str, Any], *, execute: bool) -> int | None:
    existing = context["db"]["course"].get(code)
    if existing:
        return existing["id"]
    row = context["data"]["courses"].get(code)
    if not row:
        context["skipped"].append({"entity_type": "course", "entity_key": code, "reason": "missing parsed course row"})
        return None
    values = (
        row.get("course_name"), code, _float_or_none(row.get("credits")), row.get("course_type") or "理论课",
        row.get("required_room_type") or None, _int_or_default(row.get("required_hours"), 16), row.get("raw_text") or None, ACTIVE,
    )
    context["plan"].append({"action": "create:course", "entity_key": code, "display_name": row.get("course_name"), "details": "创建课程"})
    if execute:
        cur.execute("""
            INSERT INTO course (name, code, credits, course_type, required_room_type, required_hours, description, status)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """, values)
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        row_id = cur.fetchone()["id"]
    else:
        row_id = _dry_id("course", code)
    context["db"]["course"][code] = {"id": row_id, "code": code}
    return row_id


def _create_teacher(cur, name: str, context: dict[str, Any], *, execute: bool) -> int | None:
    existing = context["db"]["teacher"].get(name)
    if existing:
        return existing["id"]
    row = context["data"]["teachers"].get(name, {})
    context["plan"].append({"action": "create:teacher", "entity_key": name, "display_name": name, "details": "创建教师"})
    if execute:
        employee_no = f"IMPORT_{name}"
        cur.execute("""
            INSERT INTO teacher (employee_no, password, role, name, department, title, status)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """, (
            employee_no,
            DEFAULT_TEACHER_PASSWORD,
            DEFAULT_TEACHER_ROLE,
            name,
            row.get("department") or _default_department(context),
            row.get("title") or None,
            ACTIVE,
        ))
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        row_id = cur.fetchone()["id"]
    else:
        row_id = _dry_id("teacher", name)
    context["db"]["teacher"][name] = {"id": row_id, "name": name}
    return row_id


def _create_classroom(cur, name: str, context: dict[str, Any], *, execute: bool) -> int | None:
    existing = context["db"]["classroom"].get(name)
    if existing:
        return existing["id"]
    row = context["data"]["classrooms"].get(name)
    if not row:
        context["skipped"].append({"entity_type": "classroom", "entity_key": name, "reason": "missing parsed classroom row"})
        return None
    context["plan"].append({"action": "create:classroom", "entity_key": name, "display_name": name, "details": "创建教室"})
    if execute:
        cur.execute("""
            INSERT INTO classroom (name, building, capacity, classroom_type, status)
            VALUES (%s, %s, %s, %s, %s)
        """, (name, None, _int_or_default(row.get("capacity"), 80), row.get("classroom_type") or "普通教室", row.get("status") or ACTIVE))
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        row_id = cur.fetchone()["id"]
    else:
        row_id = _dry_id("classroom", name)
    context["db"]["classroom"][name] = {"id": row_id, "name": name}
    return row_id


def _create_class_group(cur, name: str, context: dict[str, Any], *, execute: bool) -> int | None:
    existing = context["db"]["class_group"].get(name)
    if existing:
        return existing["id"]
    row = context["data"]["class_groups"].get(name)
    if not row:
        context["skipped"].append({"entity_type": "class_group", "entity_key": name, "reason": "missing parsed class group row"})
        return None
    context["plan"].append({"action": "create:class_group", "entity_key": name, "display_name": name, "details": "创建班级"})
    if execute:
        cur.execute("""
            INSERT INTO class_group (name, major, department, grade, student_count)
            VALUES (%s, %s, %s, %s, %s)
        """, (name, row.get("major") or None, row.get("department") or None, row.get("grade") or None, _int_or_default(row.get("student_count"), 0)))
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        row_id = cur.fetchone()["id"]
    else:
        row_id = _dry_id("class_group", name)
    context["db"]["class_group"][name] = {"id": row_id, "name": name}
    return row_id


def _create_teaching_task(cur, review_row: dict[str, str], context: dict[str, Any], *, execute: bool) -> int | None:
    entity_key = _clean(review_row.get("entity_key"))
    row = _find_task_row(entity_key, context["data"]["teaching_tasks"])
    if not row:
        context["skipped"].append(_skip(review_row, "missing parsed teaching task row"))
        return None
    schedulable = _clean(row.get("schedulable")).lower()
    exclude_reason = _clean(row.get("exclude_reason"))
    total_hours = _int_or_default(row.get("total_hours"), 0)
    if schedulable == "false":
        context["skipped"].append(_skip(review_row, f"teaching task marked unschedulable: {exclude_reason or 'no normal placement needed'}"))
        return None
    if total_hours <= 0:
        context["skipped"].append(_skip(review_row, "teaching task has no positive total_hours"))
        return None
    course = context["db"]["course"].get(row.get("course_code"))
    class_names = _split_names(row.get("class_names") or row.get("class_name"))
    class_groups = [context["db"]["class_group"].get(name) for name in class_names]
    teacher_names = _split_names(row.get("teacher_name"))
    teachers = [context["db"]["teacher"].get(name) for name in teacher_names]
    if not course or not class_groups or any(item is None for item in class_groups) or not teachers or any(item is None for item in teachers):
        context["skipped"].append(_skip(review_row, "dependencies not resolved"))
        return None
    primary_teacher_id = teachers[0]["id"]
    assistant_teacher_id = teachers[1]["id"] if len(teachers) > 1 else None
    notes = "imported_from_schedule_excel"
    context["plan"].append({"action": "create:teaching_task", "entity_key": entity_key, "display_name": review_row.get("display_name"), "details": "创建教学任务"})
    if execute:
        cur.execute("""
            INSERT INTO teaching_task (course_id, primary_teacher_id, assistant_teacher_id, classroom_id, total_hours, required_room_type, task_batch, notes, status)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """, (
            course["id"], primary_teacher_id, assistant_teacher_id, None, total_hours,
            row.get("required_room_type") or None, row.get("task_batch") or "DEFAULT",
            notes, ACTIVE,
        ))
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        task_id = cur.fetchone()["id"]
        for class_group in class_groups:
            cur.execute("INSERT INTO teaching_task_class_group (teaching_task_id, class_group_id) VALUES (%s, %s)", (task_id, class_group["id"]))
        return task_id
    return None


def _default_department(context: dict[str, Any]) -> str:
    for row in context.get("data", {}).get("class_groups", {}).values():
        department = _clean(row.get("department"))
        if department:
            return department
    return "电子信息与计算机工程系"


def _find_task_row(entity_key: str, rows: list[dict[str, str]]) -> dict[str, str] | None:
    for row in rows:
        class_names = ",".join(_split_names(row.get("class_names") or row.get("class_name")))
        teacher_names = ",".join(_split_names(row.get("teacher_name")))
        key = f"{row.get('course_code')}|{class_names}|{teacher_names}"
        if key == entity_key:
            return row
    return None


def _load_db(cur) -> dict[str, dict[str, dict[str, Any]]]:
    return {
        "course": {_clean(row["code"]): row for row in _fetch(cur, "SELECT id, code, name FROM course") if _clean(row.get("code"))},
        "teacher": {_clean(row["name"]): row for row in _fetch(cur, "SELECT id, name FROM teacher") if _clean(row.get("name"))},
        "classroom": {_clean(row["name"]): row for row in _fetch(cur, "SELECT id, name FROM classroom") if _clean(row.get("name"))},
        "class_group": {_clean(row["name"]): row for row in _fetch(cur, "SELECT id, name FROM class_group") if _clean(row.get("name"))},
    }


def _fetch(cur, sql: str) -> list[dict[str, Any]]:
    cur.execute(sql)
    return list(cur.fetchall())


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def _index(rows: list[dict[str, str]], key_field: str) -> dict[str, dict[str, str]]:
    return {_clean(row.get(key_field)): row for row in rows if _clean(row.get(key_field))}


def _plan(row: dict[str, str], action: str, details: str) -> dict[str, Any]:
    return {"action": action, "entity_type": row.get("entity_type"), "entity_key": row.get("entity_key"), "display_name": row.get("display_name"), "details": details}


def _skip(row: dict[str, str], reason: str) -> dict[str, Any]:
    return {"entity_type": row.get("entity_type"), "entity_key": row.get("entity_key"), "display_name": row.get("display_name"), "reason": reason}


def _counts(rows: list[dict[str, Any]], key: str) -> dict[str, int]:
    result: dict[str, int] = {}
    for row in rows:
        value = str(row.get(key) or "")
        result[value] = result.get(value, 0) + 1
    return dict(sorted(result.items()))


def _dry_id(entity_type: str, key: str) -> int:
    return -(abs(hash(f"{entity_type}:{key}")) % 1_000_000_000 + 1)


def _typed_value(value: str, field_name: str) -> Any:
    if field_name in {"required_hours", "capacity", "student_count"}:
        return _int_or_default(value, 0)
    if field_name == "credits":
        return _float_or_none(value)
    return value or None


def _int_or_default(value: Any, default: int) -> int:
    try:
        return int(float(str(value).strip()))
    except (TypeError, ValueError):
        return default


def _float_or_none(value: Any) -> float | None:
    try:
        return float(str(value).strip())
    except (TypeError, ValueError):
        return None


def _split_names(value: Any) -> list[str]:
    text = str(value or "").replace("，", ",").replace("、", ",")
    return [_clean(item) for item in text.split(",") if _clean(item)]


def _clean(value: Any) -> str:
    return str(value or "").strip()


def main() -> None:
    parser = argparse.ArgumentParser(description="Apply reviewed schedule import decisions.")
    parser.add_argument("--input-dir", required=True)
    parser.add_argument("--execute", action="store_true")
    args = parser.parse_args()
    report = apply_review(input_dir=Path(args.input_dir), execute=args.execute)
    print(json.dumps({k: v for k, v in report.items() if k not in {"planned_preview", "skipped_preview"}}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
