"""Apply human-reviewed schedule import decisions.

Input directory should contain:
- courses.csv / teachers.csv / classrooms.csv / class_groups.csv / teaching_tasks.csv
- import_review_items.csv generated by prepare_import_review.py and manually filled in `decision`

Safety:
- Dry-run by default.
- Use --execute to write database changes.
- Rows without decision are skipped.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from app.db.session import connect, load_db_config  # noqa: E402

ACTIVE = "ACTIVE"
DEFAULT_TEACHER_ROLE = "TEACHER"
DEFAULT_TEACHER_PASSWORD = "123456"


def apply_review(*, input_dir: Path, execute: bool = False) -> dict[str, Any]:
    if not input_dir.exists() or not input_dir.is_dir():
        raise SystemExit(f"input-dir not found: {input_dir}")

    data = {
        "courses": _index(_read_csv(input_dir / "courses.csv"), "course_code"),
        "teachers": _index(_read_csv(input_dir / "teachers.csv"), "teacher_name"),
        "classrooms": _index(_read_csv(input_dir / "classrooms.csv"), "classroom_name"),
        "class_groups": _index(_read_csv(input_dir / "class_groups.csv"), "class_name"),
        "teaching_tasks": _read_csv(input_dir / "teaching_tasks.csv"),
        "review_items": _read_csv(input_dir / "import_review_items.csv"),
    }

    decisions = [row for row in data["review_items"] if _clean(row.get("decision"))]
    plan: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []

    conn = connect(load_db_config())
    try:
        with conn.cursor() as cur:
            db = _load_db(cur)
            conn.begin()
            context = {"db": db, "data": data, "plan": plan, "skipped": skipped}
            for row in decisions:
                _apply_decision(cur, row, context, execute=execute)
            if execute:
                conn.commit()
            else:
                conn.rollback()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

    outcome = _categorize(data["review_items"], plan, skipped)
    report = {
        "status": "applied" if execute else "dry_run_ok",
        "execute": execute,
        "input_dir": str(input_dir),
        "decision_count": len(decisions),
        "planned_count": len(plan),
        "skipped_count": len(skipped),
        "outcome_counts": outcome,
        "planned_counts": _counts(plan, "action"),
        "skipped_counts": _counts(skipped, "reason"),
        "planned_preview": plan[:80],
        "skipped_preview": skipped[:80],
    }
    if execute:
        report["import_batch_id"] = _record_batch(
            input_dir=input_dir,
            data=data,
            decisions=decisions,
            outcome=outcome,
            report=report,
        )
    (input_dir / "import_apply_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    return report


def _categorize(review_items: list[dict[str, str]], plan: list[dict[str, Any]], skipped: list[dict[str, Any]]) -> dict[str, int]:
    """把一次导入的结果分成新增 / 更新 / 冲突 / 异常 / 跳过五类。

    冲突是复核项本身的属性（有多少字段两边不一致），另外四类是这次执行的去向。
    异常与跳过要分开：跳过是人工明确说"不动"，异常是系统没能应用（依赖没解析出来、
    字段不支持自动落库、merge 没填值），后者必须留在报告里让人看见。
    """
    explicit_skip = sum(1 for item in plan if item.get("action", "").startswith(("ignore:", "keep_db:")))
    return {
        "created": sum(1 for item in plan if item.get("action", "").startswith("create:")),
        "updated": sum(1 for item in plan if item.get("action", "").startswith("update:")),
        "conflicts": sum(1 for row in review_items if _clean(row.get("review_type")) == "conflict"),
        "anomalies": len(skipped),
        "skipped": explicit_skip,
    }


def _record_batch(
    *,
    input_dir: Path,
    data: dict[str, Any],
    decisions: list[dict[str, str]],
    outcome: dict[str, int],
    report: dict[str, Any],
) -> int | None:
    """把这次落库记进 import_batch 台账。

    台账失败不能反过来把已经提交的导入回滚掉——数据已经在库里了，
    丢掉台账行只是少了一条来源记录，谎报导入失败要糟糕得多。
    """
    task_batches = sorted({
        _clean(row.get("task_batch")) for row in data["teaching_tasks"] if _clean(row.get("task_batch"))
    })
    summary = {
        "outcome_counts": outcome,
        "planned_counts": report["planned_counts"],
        "skipped_counts": report["skipped_counts"],
        "task_batches": task_batches,
    }
    conn = connect(load_db_config())
    try:
        with conn.cursor() as cur:
            conn.begin()
            cur.execute(
                """
                INSERT INTO import_batch (source_name, source_kind, task_batch, imported_by, status,
                                          decision_count, created_count, updated_count, conflict_count,
                                          anomaly_count, skipped_count, summary_json)
                VALUES (%s, %s, %s, %s, 'APPLIED', %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    str(input_dir), "DIRECTORY",
                    task_batches[0] if task_batches else "DEFAULT",
                    os.getenv("EDU_FLOW_IMPORT_OPERATOR", "local-demo-operator"),
                    len(decisions), outcome["created"], outcome["updated"], outcome["conflicts"],
                    outcome["anomalies"], outcome["skipped"],
                    json.dumps(summary, ensure_ascii=False),
                ),
            )
            cur.execute("SELECT LAST_INSERT_ID() AS id")
            batch_id = int(cur.fetchone()["id"])
            conn.commit()
            return batch_id
    except Exception as exception:  # noqa: BLE001 - 台账写入失败不应回滚已提交的导入
        print(f"[IMPORT] 导入已落库，但 import_batch 台账写入失败: {exception}", file=sys.stderr, flush=True)
        return None
    finally:
        conn.close()


def _apply_decision(cur, row: dict[str, str], context: dict[str, Any], *, execute: bool) -> None:
    decision = _clean(row.get("decision"))
    entity_type = _clean(row.get("entity_type"))
    entity_key = _clean(row.get("entity_key"))
    review_type = _clean(row.get("review_type"))
    if decision in {"ignore", "keep_db"}:
        context["plan"].append(_plan(row, f"{decision}:{entity_type}", "不修改数据库"))
        return
    if review_type == "conflict" and decision in {"use_import", "merge"}:
        _apply_conflict_value(cur, row, context, execute=execute)
        return
    if review_type == "new_item" and decision in {"create", "create_after_dependencies"}:
        if entity_type == "course":
            _create_course(cur, entity_key, context, execute=execute)
            return
        if entity_type == "teacher":
            _create_teacher(cur, entity_key, context, execute=execute)
            return
        if entity_type == "class_group":
            _create_class_group(cur, entity_key, context, execute=execute)
            return
        if entity_type == "classroom":
            _create_classroom(cur, entity_key, context, execute=execute)
            return
        if entity_type == "teaching_task":
            _create_teaching_task(cur, row, context, execute=execute)
            return
    context["skipped"].append(_skip(row, f"unsupported decision: {decision}"))


def _apply_conflict_value(cur, row: dict[str, str], context: dict[str, Any], *, execute: bool) -> None:
    """把一个字段冲突的最终取值落库。

    use_import 采用导入值；merge 采用复核人在 merged_value 里写下的第三个值
    （例如两边都不完全对，人工给出正确的教室容量）。merge 没写值等同于没有决定，
    必须显式拒绝而不是悄悄退回导入值。
    """
    entity_type = _clean(row.get("entity_type"))
    entity_key = _clean(row.get("entity_key"))
    field_name = _clean(row.get("field_name"))
    decision = _clean(row.get("decision"))
    merged_value = _clean(row.get("merged_value"))
    if decision == "merge" and not merged_value:
        context["skipped"].append(_skip(row, "merge decision without merged_value"))
        return
    import_value = merged_value if decision == "merge" else _clean(row.get("import_value"))
    db_id = _clean(row.get("db_id"))
    sql_map = {
        ("course", "course_name"): ("course", "name"),
        ("course", "credits"): ("course", "credits"),
        ("course", "required_hours"): ("course", "required_hours"),
        ("course", "course_type"): ("course", "course_type"),
        ("course", "required_room_type"): ("course", "required_room_type"),
        ("classroom", "classroom_type"): ("classroom", "classroom_type"),
        ("classroom", "capacity"): ("classroom", "capacity"),
        ("classroom", "status"): ("classroom", "status"),
        ("class_group", "major"): ("class_group", "major"),
        ("class_group", "department"): ("class_group", "department"),
        ("class_group", "grade"): ("class_group", "grade"),
        ("class_group", "student_count"): ("class_group", "student_count"),
    }
    target = sql_map.get((entity_type, field_name))
    if not target or not db_id:
        context["skipped"].append(_skip(row, "conflict field cannot be applied automatically"))
        return
    table, column = target
    value = _typed_value(import_value, field_name)
    source = "人工合并值" if decision == "merge" else "导入值"
    context["plan"].append(_plan(row, f"update:{table}.{column}", f"{entity_key}: {column} = {value}（{source}）"))
    if execute:
        cur.execute(f"UPDATE {table} SET {column} = %s WHERE id = %s", (value, db_id))


def _create_course(cur, code: str, context: dict[str, Any], *, execute: bool) -> int | None:
    existing = context["db"]["course"].get(code)
    if existing:
        return existing["id"]
    row = context["data"]["courses"].get(code)
    if not row:
        context["skipped"].append({"entity_type": "course", "entity_key": code, "reason": "missing parsed course row"})
        return None
    values = (
        row.get("course_name"), code, _float_or_none(row.get("credits")), row.get("course_type") or "理论课",
        row.get("required_room_type") or None, _int_or_default(row.get("required_hours"), 16), row.get("raw_text") or None, ACTIVE,
    )
    context["plan"].append({"action": "create:course", "entity_key": code, "display_name": row.get("course_name"), "details": "创建课程"})
    if execute:
        cur.execute("""
            INSERT INTO course (name, code, credits, course_type, required_room_type, required_hours, description, status)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """, values)
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        row_id = cur.fetchone()["id"]
    else:
        row_id = _dry_id("course", code)
    context["db"]["course"][code] = {"id": row_id, "code": code}
    return row_id


def _create_teacher(cur, name: str, context: dict[str, Any], *, execute: bool) -> int | None:
    existing = context["db"]["teacher"].get(name)
    if existing:
        return existing["id"]
    row = context["data"]["teachers"].get(name, {})
    context["plan"].append({"action": "create:teacher", "entity_key": name, "display_name": name, "details": "创建教师"})
    if execute:
        employee_no = f"IMPORT_{name}"
        cur.execute("""
            INSERT INTO teacher (employee_no, password, role, name, department, title, status)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """, (
            employee_no,
            DEFAULT_TEACHER_PASSWORD,
            DEFAULT_TEACHER_ROLE,
            name,
            row.get("department") or _default_department(context),
            row.get("title") or None,
            ACTIVE,
        ))
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        row_id = cur.fetchone()["id"]
    else:
        row_id = _dry_id("teacher", name)
    context["db"]["teacher"][name] = {"id": row_id, "name": name}
    return row_id


def _create_classroom(cur, name: str, context: dict[str, Any], *, execute: bool) -> int | None:
    existing = context["db"]["classroom"].get(name)
    if existing:
        return existing["id"]
    row = context["data"]["classrooms"].get(name)
    if not row:
        context["skipped"].append({"entity_type": "classroom", "entity_key": name, "reason": "missing parsed classroom row"})
        return None
    context["plan"].append({"action": "create:classroom", "entity_key": name, "display_name": name, "details": "创建教室"})
    if execute:
        cur.execute("""
            INSERT INTO classroom (name, building, capacity, classroom_type, status)
            VALUES (%s, %s, %s, %s, %s)
        """, (name, None, _int_or_default(row.get("capacity"), 80), row.get("classroom_type") or "普通教室", row.get("status") or ACTIVE))
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        row_id = cur.fetchone()["id"]
    else:
        row_id = _dry_id("classroom", name)
    context["db"]["classroom"][name] = {"id": row_id, "name": name}
    return row_id


def _create_class_group(cur, name: str, context: dict[str, Any], *, execute: bool) -> int | None:
    existing = context["db"]["class_group"].get(name)
    if existing:
        return existing["id"]
    row = context["data"]["class_groups"].get(name)
    if not row:
        context["skipped"].append({"entity_type": "class_group", "entity_key": name, "reason": "missing parsed class group row"})
        return None
    context["plan"].append({"action": "create:class_group", "entity_key": name, "display_name": name, "details": "创建班级"})
    if execute:
        cur.execute("""
            INSERT INTO class_group (name, major, department, grade, student_count)
            VALUES (%s, %s, %s, %s, %s)
        """, (name, row.get("major") or None, row.get("department") or None, row.get("grade") or None, _int_or_default(row.get("student_count"), 0)))
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        row_id = cur.fetchone()["id"]
    else:
        row_id = _dry_id("class_group", name)
    context["db"]["class_group"][name] = {"id": row_id, "name": name}
    return row_id


def _create_teaching_task(cur, review_row: dict[str, str], context: dict[str, Any], *, execute: bool) -> int | None:
    entity_key = _clean(review_row.get("entity_key"))
    row = _find_task_row(entity_key, context["data"]["teaching_tasks"])
    if not row:
        context["skipped"].append(_skip(review_row, "missing parsed teaching task row"))
        return None
    schedulable = _clean(row.get("schedulable")).lower()
    exclude_reason = _clean(row.get("exclude_reason"))
    total_hours = _int_or_default(row.get("total_hours"), 0)
    if schedulable == "false":
        context["skipped"].append(_skip(review_row, f"teaching task marked unschedulable: {exclude_reason or 'no normal placement needed'}"))
        return None
    if total_hours <= 0:
        context["skipped"].append(_skip(review_row, "teaching task has no positive total_hours"))
        return None
    course = context["db"]["course"].get(row.get("course_code"))
    class_names = _split_names(row.get("class_names") or row.get("class_name"))
    class_groups = [context["db"]["class_group"].get(name) for name in class_names]
    teacher_names = _split_names(row.get("teacher_name"))
    teachers = [context["db"]["teacher"].get(name) for name in teacher_names]
    if not course or not class_groups or any(item is None for item in class_groups) or not teachers or any(item is None for item in teachers):
        context["skipped"].append(_skip(review_row, "dependencies not resolved"))
        return None
    primary_teacher_id = teachers[0]["id"]
    assistant_teacher_id = teachers[1]["id"] if len(teachers) > 1 else None
    pattern = _importable_pattern(row, total_hours)
    notes = "imported_from_schedule_excel"
    if pattern["note"]:
        notes = f"{notes}; {pattern['note']}"
    context["plan"].append({
        "action": "create:teaching_task",
        "entity_key": entity_key,
        "display_name": review_row.get("display_name"),
        "details": "创建教学任务" + ("（含课表节奏）" if pattern["sessions_per_week"] else "（节奏待人工确认）"),
    })
    if execute:
        cur.execute("""
            INSERT INTO teaching_task (course_id, primary_teacher_id, assistant_teacher_id, classroom_id, total_hours,
                                       sessions_per_week, duration_weeks, required_room_type, task_batch, notes, status)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """, (
            course["id"], primary_teacher_id, assistant_teacher_id, None, total_hours,
            pattern["sessions_per_week"], pattern["duration_weeks"],
            row.get("required_room_type") or None, row.get("task_batch") or "DEFAULT",
            notes, ACTIVE,
        ))
        cur.execute("SELECT LAST_INSERT_ID() AS id")
        task_id = cur.fetchone()["id"]
        for class_group in class_groups:
            cur.execute("INSERT INTO teaching_task_class_group (teaching_task_id, class_group_id) VALUES (%s, %s)", (task_id, class_group["id"]))
        return task_id
    return None


def _importable_pattern(row: dict[str, str], total_hours: int) -> dict[str, Any]:
    """课表网格给出的教学节奏，只在它自洽时才写进库。

    `teaching_task` 的入口校验要求 每周次数 × 持续周数 × 每次课时 == 总课时。
    真实数据里声明课时和课表实测课时经常对不上（节假日停课、补课、课程说明本身
    就是计划值），此时不能猜：把节奏留空让引擎按课时推导，并在 notes 里写清楚
    实测值，交由人工确认。静默写入一个不自洽的 pattern 会让课时审计从一开始就错。
    """
    empty = {"sessions_per_week": None, "duration_weeks": None, "note": ""}
    sessions = _int_or_default(row.get("sessions_per_week"), 0)
    weeks = _int_or_default(row.get("duration_weeks"), 0)
    session_slots = _int_or_default(row.get("session_slots"), 0)
    observed = _int_or_default(row.get("observed_hours"), 0)
    if not sessions or not weeks or not session_slots:
        return empty
    if _clean(row.get("pattern_regular")) != "true":
        return {**empty, "note": f"课表节奏不规则(每周{sessions}次×{weeks}周, 实测{observed}课时)，待人工确认"}
    if observed != total_hours:
        return {**empty, "note": f"声明{total_hours}课时与课表实测{observed}课时不一致，节奏待人工确认"}
    if sessions * weeks * session_slots != total_hours:
        return {**empty, "note": f"课表节奏与总课时不自洽(每周{sessions}次×{weeks}周×每次{session_slots}节≠{total_hours})，待人工确认"}
    return {
        "sessions_per_week": sessions,
        "duration_weeks": weeks,
        "note": f"节奏来自课表(每周{sessions}次×{weeks}周×每次{session_slots}节)",
    }


def _default_department(context: dict[str, Any]) -> str:
    for row in context.get("data", {}).get("class_groups", {}).values():
        department = _clean(row.get("department"))
        if department:
            return department
    return "电子信息与计算机工程系"


def _find_task_row(entity_key: str, rows: list[dict[str, str]]) -> dict[str, str] | None:
    for row in rows:
        class_names = ",".join(_split_names(row.get("class_names") or row.get("class_name")))
        teacher_names = ",".join(_split_names(row.get("teacher_name")))
        key = f"{row.get('course_code')}|{class_names}|{teacher_names}"
        if key == entity_key:
            return row
    return None


def _load_db(cur) -> dict[str, dict[str, dict[str, Any]]]:
    return {
        "course": {_clean(row["code"]): row for row in _fetch(cur, "SELECT id, code, name FROM course") if _clean(row.get("code"))},
        "teacher": {_clean(row["name"]): row for row in _fetch(cur, "SELECT id, name FROM teacher") if _clean(row.get("name"))},
        "classroom": {_clean(row["name"]): row for row in _fetch(cur, "SELECT id, name FROM classroom") if _clean(row.get("name"))},
        "class_group": {_clean(row["name"]): row for row in _fetch(cur, "SELECT id, name FROM class_group") if _clean(row.get("name"))},
    }


def _fetch(cur, sql: str) -> list[dict[str, Any]]:
    cur.execute(sql)
    return list(cur.fetchall())


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def _index(rows: list[dict[str, str]], key_field: str) -> dict[str, dict[str, str]]:
    return {_clean(row.get(key_field)): row for row in rows if _clean(row.get(key_field))}


def _plan(row: dict[str, str], action: str, details: str) -> dict[str, Any]:
    return {"action": action, "entity_type": row.get("entity_type"), "entity_key": row.get("entity_key"), "display_name": row.get("display_name"), "details": details}


def _skip(row: dict[str, str], reason: str) -> dict[str, Any]:
    return {"entity_type": row.get("entity_type"), "entity_key": row.get("entity_key"), "display_name": row.get("display_name"), "reason": reason}


def _counts(rows: list[dict[str, Any]], key: str) -> dict[str, int]:
    result: dict[str, int] = {}
    for row in rows:
        value = str(row.get(key) or "")
        result[value] = result.get(value, 0) + 1
    return dict(sorted(result.items()))


def _dry_id(entity_type: str, key: str) -> int:
    return -(abs(hash(f"{entity_type}:{key}")) % 1_000_000_000 + 1)


def _typed_value(value: str, field_name: str) -> Any:
    if field_name in {"required_hours", "capacity", "student_count"}:
        return _int_or_default(value, 0)
    if field_name == "credits":
        return _float_or_none(value)
    return value or None


def _int_or_default(value: Any, default: int) -> int:
    try:
        return int(float(str(value).strip()))
    except (TypeError, ValueError):
        return default


def _float_or_none(value: Any) -> float | None:
    try:
        return float(str(value).strip())
    except (TypeError, ValueError):
        return None


def _split_names(value: Any) -> list[str]:
    text = str(value or "").replace("，", ",").replace("、", ",")
    return [_clean(item) for item in text.split(",") if _clean(item)]


def _clean(value: Any) -> str:
    return str(value or "").strip()


def main() -> None:
    parser = argparse.ArgumentParser(description="Apply reviewed schedule import decisions.")
    parser.add_argument("--input-dir", required=True)
    parser.add_argument("--execute", action="store_true")
    args = parser.parse_args()
    report = apply_review(input_dir=Path(args.input_dir), execute=args.execute)
    print(json.dumps({k: v for k, v in report.items() if k not in {"planned_preview", "skipped_preview"}}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
