"""Prepare human-review decision CSV from schedule import analysis outputs.

Input directory should contain files generated by analyze_schedule_import.py:
- import_conflicts.csv
- import_new_items.csv
- import_matched_items.csv

Output:
- import_review_items.csv
- import_review_report.json

This script is read-only. It does not modify database rows.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from pathlib import Path
from typing import Any

REVIEW_FIELDS = [
    "review_id",
    "review_type",
    "entity_type",
    "entity_key",
    "display_name",
    "field_name",
    "field_label",
    "db_id",
    "db_value",
    "import_value",
    "status",
    "decision",
    "allowed_decisions",
    "recommended_decision",
    "reason",
    "review_note",
]

DECISIONS = {
    "conflict": "keep_db,use_import,ignore",
    "new_item": "create,ignore",
    "teaching_task": "create_after_dependencies,create,ignore",
}


def prepare_review(*, input_dir: Path, output_dir: Path | None = None) -> dict[str, Any]:
    if not input_dir.exists() or not input_dir.is_dir():
        raise SystemExit(f"input-dir not found: {input_dir}")
    output_dir = output_dir or input_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    conflicts = _dedupe_rows(_read_csv(input_dir / "import_conflicts.csv"), ["entity_type", "entity_key", "field_name"])
    new_items = _dedupe_rows(_read_csv(input_dir / "import_new_items.csv"), ["entity_type", "entity_key"])
    review_items: list[dict[str, Any]] = []

    for row in conflicts:
        review_items.append({
            "review_id": _review_id("C", len(review_items) + 1),
            "review_type": "conflict",
            "entity_type": row.get("entity_type", ""),
            "entity_key": row.get("entity_key", ""),
            "display_name": row.get("display_name", ""),
            "field_name": row.get("field_name", ""),
            "field_label": row.get("field_label", ""),
            "db_id": row.get("db_id", ""),
            "db_value": row.get("db_value", ""),
            "import_value": row.get("import_value", ""),
            "status": "PENDING_CONFLICT",
            "decision": "",
            "allowed_decisions": DECISIONS["conflict"],
            "recommended_decision": _recommend_conflict(row),
            "reason": row.get("reason", ""),
            "review_note": "",
        })

    for row in new_items:
        review_items.append({
            "review_id": _review_id("N", len(review_items) + 1),
            "review_type": "new_item",
            "entity_type": row.get("entity_type", ""),
            "entity_key": row.get("entity_key", ""),
            "display_name": row.get("display_name", ""),
            "field_name": "",
            "field_label": "",
            "db_id": "",
            "db_value": "",
            "import_value": row.get("display_name", ""),
            "status": "PENDING_CREATE",
            "decision": "",
            "allowed_decisions": _allowed_decisions_for_new_item(row),
            "recommended_decision": _recommend_new_item(row),
            "reason": row.get("reason", ""),
            "review_note": "",
        })

    output_path = output_dir / "import_review_items.csv"
    _write_csv(output_path, review_items, REVIEW_FIELDS)

    report = {
        "status": "needs_review" if review_items else "ok",
        "input_dir": str(input_dir),
        "output_dir": str(output_dir),
        "files": {
            "review_items": str(output_path),
        },
        "counts": {
            "review_items": len(review_items),
            "conflicts": len(conflicts),
            "new_items": len(new_items),
        },
        "review_type_counts": dict(Counter(item["review_type"] for item in review_items).most_common()),
        "entity_type_counts": dict(Counter(item["entity_type"] for item in review_items).most_common()),
        "recommended_decision_counts": dict(Counter(item["recommended_decision"] for item in review_items).most_common()),
        "preview": review_items[:50],
    }
    (output_dir / "import_review_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    return report


def _allowed_decisions_for_new_item(row: dict[str, str]) -> str:
    if row.get("entity_type") == "teaching_task":
        return DECISIONS["teaching_task"]
    return DECISIONS["new_item"]


def _recommend_conflict(row: dict[str, str]) -> str:
    entity_type = row.get("entity_type", "")
    field_name = row.get("field_name", "")
    if entity_type == "classroom" and field_name == "classroom_type":
        return "keep_db"
    return "keep_db"


def _recommend_new_item(row: dict[str, str]) -> str:
    entity_type = row.get("entity_type", "")
    if entity_type == "teaching_task":
        return "create_after_dependencies"
    return "create"


def _review_id(prefix: str, number: int) -> str:
    return f"{prefix}{number:04d}"


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def _dedupe_rows(rows: list[dict[str, str]], key_fields: list[str]) -> list[dict[str, str]]:
    seen = set()
    result = []
    for row in rows:
        key = tuple((row.get(field) or "").strip() for field in key_fields)
        if key in seen:
            continue
        seen.add(key)
        result.append(row)
    return result


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare schedule import review decision CSV.")
    parser.add_argument("--input-dir", required=True)
    parser.add_argument("--output-dir", default=None)
    args = parser.parse_args()
    report = prepare_review(
        input_dir=Path(args.input_dir),
        output_dir=Path(args.output_dir) if args.output_dir else None,
    )
    print(json.dumps({k: v for k, v in report.items() if k != "preview"}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
