/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTimetableRouteImport } from './routes/admin/timetable'
import { Route as AdminTeachingTasksRouteImport } from './routes/admin/teaching-tasks'
import { Route as AdminTeachersRouteImport } from './routes/admin/teachers'
import { Route as AdminTeacherProfilesRouteImport } from './routes/admin/teacher-profiles'
import { Route as AdminSimulationRouteImport } from './routes/admin/simulation'
import { Route as AdminModelTrainingRouteImport } from './routes/admin/model-training'
import { Route as AdminImportReviewRouteImport } from './routes/admin/import-review'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminConstraintEditorRouteImport } from './routes/admin/constraint-editor'
import { Route as AdminClassroomsRouteImport } from './routes/admin/classrooms'
import { Route as AdminClassGroupsRouteImport } from './routes/admin/class-groups'
import { Route as AdminAllocationRouteImport } from './routes/admin/allocation'
import { Route as AdminAdjustmentRouteImport } from './routes/admin/adjustment'
import { Route as AdminAllocationSchemesSchemeIdRouteImport } from './routes/admin/allocation.schemes.$schemeId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachingTasksRoute = AdminTeachingTasksRouteImport.update({
  id: '/teaching-tasks',
  path: '/teaching-tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeacherProfilesRoute = AdminTeacherProfilesRouteImport.update({
  id: '/teacher-profiles',
  path: '/teacher-profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSimulationRoute = AdminSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelTrainingRoute = AdminModelTrainingRouteImport.update({
  id: '/model-training',
  path: '/model-training',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportReviewRoute = AdminImportReviewRouteImport.update({
  id: '/import-review',
  path: '/import-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConstraintEditorRoute = AdminConstraintEditorRouteImport.update({
  id: '/constraint-editor',
  path: '/constraint-editor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassroomsRoute = AdminClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassGroupsRoute = AdminClassGroupsRouteImport.update({
  id: '/class-groups',
  path: '/class-groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAllocationRoute = AdminAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdjustmentRoute = AdminAdjustmentRouteImport.update({
  id: '/adjustment',
  path: '/adjustment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAllocationSchemesSchemeIdRoute =
  AdminAllocationSchemesSchemeIdRouteImport.update({
    id: '/schemes/$schemeId',
    path: '/schemes/$schemeId',
    getParentRoute: () => AdminAllocationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/adjustment': typeof AdminAdjustmentRoute
  '/admin/allocation': typeof AdminAllocationRouteWithChildren
  '/admin/class-groups': typeof AdminClassGroupsRoute
  '/admin/classrooms': typeof AdminClassroomsRoute
  '/admin/constraint-editor': typeof AdminConstraintEditorRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/import-review': typeof AdminImportReviewRoute
  '/admin/model-training': typeof AdminModelTrainingRoute
  '/admin/simulation': typeof AdminSimulationRoute
  '/admin/teacher-profiles': typeof AdminTeacherProfilesRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/teaching-tasks': typeof AdminTeachingTasksRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/allocation/schemes/$schemeId': typeof AdminAllocationSchemesSchemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/adjustment': typeof AdminAdjustmentRoute
  '/admin/allocation': typeof AdminAllocationRouteWithChildren
  '/admin/class-groups': typeof AdminClassGroupsRoute
  '/admin/classrooms': typeof AdminClassroomsRoute
  '/admin/constraint-editor': typeof AdminConstraintEditorRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/import-review': typeof AdminImportReviewRoute
  '/admin/model-training': typeof AdminModelTrainingRoute
  '/admin/simulation': typeof AdminSimulationRoute
  '/admin/teacher-profiles': typeof AdminTeacherProfilesRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/teaching-tasks': typeof AdminTeachingTasksRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/allocation/schemes/$schemeId': typeof AdminAllocationSchemesSchemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/adjustment': typeof AdminAdjustmentRoute
  '/admin/allocation': typeof AdminAllocationRouteWithChildren
  '/admin/class-groups': typeof AdminClassGroupsRoute
  '/admin/classrooms': typeof AdminClassroomsRoute
  '/admin/constraint-editor': typeof AdminConstraintEditorRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/import-review': typeof AdminImportReviewRoute
  '/admin/model-training': typeof AdminModelTrainingRoute
  '/admin/simulation': typeof AdminSimulationRoute
  '/admin/teacher-profiles': typeof AdminTeacherProfilesRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/teaching-tasks': typeof AdminTeachingTasksRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/allocation/schemes/$schemeId': typeof AdminAllocationSchemesSchemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/adjustment'
    | '/admin/allocation'
    | '/admin/class-groups'
    | '/admin/classrooms'
    | '/admin/constraint-editor'
    | '/admin/courses'
    | '/admin/import-review'
    | '/admin/model-training'
    | '/admin/simulation'
    | '/admin/teacher-profiles'
    | '/admin/teachers'
    | '/admin/teaching-tasks'
    | '/admin/timetable'
    | '/admin/allocation/schemes/$schemeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/adjustment'
    | '/admin/allocation'
    | '/admin/class-groups'
    | '/admin/classrooms'
    | '/admin/constraint-editor'
    | '/admin/courses'
    | '/admin/import-review'
    | '/admin/model-training'
    | '/admin/simulation'
    | '/admin/teacher-profiles'
    | '/admin/teachers'
    | '/admin/teaching-tasks'
    | '/admin/timetable'
    | '/admin/allocation/schemes/$schemeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/adjustment'
    | '/admin/allocation'
    | '/admin/class-groups'
    | '/admin/classrooms'
    | '/admin/constraint-editor'
    | '/admin/courses'
    | '/admin/import-review'
    | '/admin/model-training'
    | '/admin/simulation'
    | '/admin/teacher-profiles'
    | '/admin/teachers'
    | '/admin/teaching-tasks'
    | '/admin/timetable'
    | '/admin/allocation/schemes/$schemeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teaching-tasks': {
      id: '/admin/teaching-tasks'
      path: '/teaching-tasks'
      fullPath: '/admin/teaching-tasks'
      preLoaderRoute: typeof AdminTeachingTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teacher-profiles': {
      id: '/admin/teacher-profiles'
      path: '/teacher-profiles'
      fullPath: '/admin/teacher-profiles'
      preLoaderRoute: typeof AdminTeacherProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/simulation': {
      id: '/admin/simulation'
      path: '/simulation'
      fullPath: '/admin/simulation'
      preLoaderRoute: typeof AdminSimulationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/model-training': {
      id: '/admin/model-training'
      path: '/model-training'
      fullPath: '/admin/model-training'
      preLoaderRoute: typeof AdminModelTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import-review': {
      id: '/admin/import-review'
      path: '/import-review'
      fullPath: '/admin/import-review'
      preLoaderRoute: typeof AdminImportReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/constraint-editor': {
      id: '/admin/constraint-editor'
      path: '/constraint-editor'
      fullPath: '/admin/constraint-editor'
      preLoaderRoute: typeof AdminConstraintEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classrooms': {
      id: '/admin/classrooms'
      path: '/classrooms'
      fullPath: '/admin/classrooms'
      preLoaderRoute: typeof AdminClassroomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/class-groups': {
      id: '/admin/class-groups'
      path: '/class-groups'
      fullPath: '/admin/class-groups'
      preLoaderRoute: typeof AdminClassGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/allocation': {
      id: '/admin/allocation'
      path: '/allocation'
      fullPath: '/admin/allocation'
      preLoaderRoute: typeof AdminAllocationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/adjustment': {
      id: '/admin/adjustment'
      path: '/adjustment'
      fullPath: '/admin/adjustment'
      preLoaderRoute: typeof AdminAdjustmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/allocation/schemes/$schemeId': {
      id: '/admin/allocation/schemes/$schemeId'
      path: '/schemes/$schemeId'
      fullPath: '/admin/allocation/schemes/$schemeId'
      preLoaderRoute: typeof AdminAllocationSchemesSchemeIdRouteImport
      parentRoute: typeof AdminAllocationRoute
    }
  }
}

interface AdminAllocationRouteChildren {
  AdminAllocationSchemesSchemeIdRoute: typeof AdminAllocationSchemesSchemeIdRoute
}

const AdminAllocationRouteChildren: AdminAllocationRouteChildren = {
  AdminAllocationSchemesSchemeIdRoute: AdminAllocationSchemesSchemeIdRoute,
}

const AdminAllocationRouteWithChildren = AdminAllocationRoute._addFileChildren(
  AdminAllocationRouteChildren,
)

interface AdminRouteChildren {
  AdminAdjustmentRoute: typeof AdminAdjustmentRoute
  AdminAllocationRoute: typeof AdminAllocationRouteWithChildren
  AdminClassGroupsRoute: typeof AdminClassGroupsRoute
  AdminClassroomsRoute: typeof AdminClassroomsRoute
  AdminConstraintEditorRoute: typeof AdminConstraintEditorRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminImportReviewRoute: typeof AdminImportReviewRoute
  AdminModelTrainingRoute: typeof AdminModelTrainingRoute
  AdminSimulationRoute: typeof AdminSimulationRoute
  AdminTeacherProfilesRoute: typeof AdminTeacherProfilesRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTeachingTasksRoute: typeof AdminTeachingTasksRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdjustmentRoute: AdminAdjustmentRoute,
  AdminAllocationRoute: AdminAllocationRouteWithChildren,
  AdminClassGroupsRoute: AdminClassGroupsRoute,
  AdminClassroomsRoute: AdminClassroomsRoute,
  AdminConstraintEditorRoute: AdminConstraintEditorRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminImportReviewRoute: AdminImportReviewRoute,
  AdminModelTrainingRoute: AdminModelTrainingRoute,
  AdminSimulationRoute: AdminSimulationRoute,
  AdminTeacherProfilesRoute: AdminTeacherProfilesRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTeachingTasksRoute: AdminTeachingTasksRoute,
  AdminTimetableRoute: AdminTimetableRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
